### ISSUE TITLE
H7 based micro variant?

### ISSUE THREAD

**Issue by Coffee-Boyy** [pms67/HadesFCS#5]
Hi! First off I would like to say beautiful designs, I'm not much of a hardware designer but they sure do look beautiful.
I was wondering if an H7 based micro version would be possible? I'm trying to fit a F7/H7 inside a 5" racing drone to communicate over SPI to a AI based depth sensing camera but the F4 likely won't have enough processing power for that.

I have been looking through the designs and I think I could eventually get something cobbled together but this would be my first ever board and since you already have these two variants I thought it would be worthwhile asking you first :)

Please let me know what you think!

Thanks,
Connor

**Comment by pms67** [comment]
Hi Connor,

Thanks a lot for your message! Very glad to hear that you like the look of these designs.

A smaller H7-based system would definitely be nice and I may have a look into that in the future. There are a few (?) small H7 flight control boards out there (e.g. https://www.getfpv.com/sp-racing-h7-400mhz-extreme-dual-gyro-flight-controller.htmlhttps://www.getfpv.com/sp-racing-h7-400mhz-extreme-dual-gyro-flight-controller.html).

Is that something you're after or how come you're looking for something 'new'?

Best,
Philip

**Comment by Coffee-Boyy** [comment]
I don't know why I never realized I could just use an off the shelf flight controller for what I am doing but the one you sent over has everything I could've ever asked for. I'm actually quite pleased with the connection offerings this board has, as it even has SWD!

Thanks for showing me this board!
Connor

**Comment by pms67** [comment]
Awesome, glad that board may work for you!

Philip
